import { Guest } from './types';

export const INITIAL_GUESTS: Guest[] = [
  // Bridal Party (8 members) - all attending
  {
    id: 'g-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@gmail.com',
    phone: '+1 (415) 890-1234',
    group: 'bridal_party',
    rsvpStatus: 'attending',
    partyTag: 'Maid of Honor',
    plusOnes: 1,
    dietary: 'Vegetarian',
  },
  {
    id: 'g-2',
    name: 'Marcus Vance',
    email: 'marcus.vance@yahoo.com',
    phone: '+1 (415) 762-9841',
    group: 'bridal_party',
    rsvpStatus: 'attending',
    partyTag: 'Best Man',
    plusOnes: 1,
  },
  {
    id: 'g-3',
    name: 'Chloe Bennett',
    email: 'chloe.bennett@outlook.com',
    phone: '+1 (510) 334-9021',
    group: 'bridal_party',
    rsvpStatus: 'attending',
    partyTag: 'Bridesmaid',
    plusOnes: 0,
    dietary: 'Gluten-Free',
  },
  {
    id: 'g-4',
    name: 'Daniel Kim',
    email: 'dan.kim@gmail.com',
    phone: '+1 (650) 441-8932',
    group: 'bridal_party',
    rsvpStatus: 'attending',
    partyTag: 'Groomsman',
    plusOnes: 1,
  },
  {
    id: 'g-5',
    name: 'Aaliyah Patel',
    email: 'aaliyah.patel@icloud.com',
    phone: '+1 (408) 552-3091',
    group: 'bridal_party',
    rsvpStatus: 'attending',
    partyTag: 'Bridesmaid',
    plusOnes: 0,
  },
  {
    id: 'g-6',
    name: 'Ethan Ross',
    email: 'ethan.ross@proton.me',
    phone: '+1 (415) 609-4412',
    group: 'bridal_party',
    rsvpStatus: 'attending',
    partyTag: 'Groomsman',
    plusOnes: 1,
  },
  {
    id: 'g-7',
    name: 'Maya Lin',
    email: 'maya.lin@gmail.com',
    phone: '+1 (510) 887-2104',
    group: 'bridal_party',
    rsvpStatus: 'attending',
    partyTag: 'Bridesmaid',
    plusOnes: 0,
    dietary: 'Vegan',
  },
  {
    id: 'g-8',
    name: 'Lucas Wright',
    email: 'lucas.wright@berkeley.edu',
    phone: '+1 (415) 902-3388',
    group: 'bridal_party',
    rsvpStatus: 'attending',
    partyTag: 'Groomsman',
    plusOnes: 1,
  },

  // Other Attending Guests (26 more attending guests = 34 total attending)
  {
    id: 'g-9',
    name: 'Robert & Clara Sterling',
    email: 'clara.sterling@gmail.com',
    phone: '+1 (415) 501-8890',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Parents of the Groom',
    plusOnes: 1,
  },
  {
    id: 'g-10',
    name: 'Eleanor Harrison',
    email: 'eleanor.harrison@gmail.com',
    phone: '+1 (415) 302-7711',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Mother of the Bride',
    plusOnes: 0,
  },
  {
    id: 'g-11',
    name: 'James Harrison',
    email: 'james.harrison@stanford.edu',
    phone: '+1 (650) 882-9901',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Father of the Bride',
    plusOnes: 0,
  },
  {
    id: 'g-12',
    name: 'Alexander Novak',
    email: 'alex.novak@gmail.com',
    phone: '+1 (415) 771-4455',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Family Friend',
    plusOnes: 1,
  },
  {
    id: 'g-13',
    name: 'Jessica Gomez',
    email: 'jess.gomez@gmail.com',
    phone: '+1 (510) 901-2244',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'College Friend',
    plusOnes: 0,
    dietary: 'Nut Allergy',
  },
  {
    id: 'g-14',
    name: 'Michael Chen',
    email: 'mchen.creative@gmail.com',
    phone: '+1 (408) 723-9901',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Coworker',
    plusOnes: 1,
  },
  {
    id: 'g-15',
    name: 'Olivia Martinez',
    email: 'olivia.martinez@yahoo.com',
    phone: '+1 (415) 430-8812',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'High School Friend',
    plusOnes: 0,
  },
  {
    id: 'g-16',
    name: 'Noah Gallagher',
    email: 'noah.gallagher@outlook.com',
    phone: '+1 (415) 662-3341',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Cousin',
    plusOnes: 1,
  },
  {
    id: 'g-17',
    name: 'Emma Watson-Lee',
    email: 'emma.wl@gmail.com',
    phone: '+1 (510) 441-7890',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Aunt',
    plusOnes: 1,
  },
  {
    id: 'g-18',
    name: 'Henry Lee',
    email: 'henry.lee@gmail.com',
    phone: '+1 (510) 441-7891',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Uncle',
    plusOnes: 0,
  },
  {
    id: 'g-19',
    name: 'Grace Taylor',
    email: 'grace.taylor@apple.com',
    phone: '+1 (408) 991-2345',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Coworker',
    plusOnes: 1,
  },
  {
    id: 'g-20',
    name: 'Benjamin Cooper',
    email: 'ben.cooper@gmail.com',
    phone: '+1 (415) 789-0123',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'College Roommate',
    plusOnes: 1,
  },
  {
    id: 'g-21',
    name: 'Zoe Anderson',
    email: 'zoe.anderson@gmail.com',
    phone: '+1 (415) 554-1102',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Friend',
    plusOnes: 0,
    dietary: 'Pescatarian',
  },
  {
    id: 'g-22',
    name: 'William Foster',
    email: 'will.foster@gmail.com',
    phone: '+1 (510) 678-9900',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Neighbor',
    plusOnes: 1,
  },
  {
    id: 'g-23',
    name: 'Ava Sinclair',
    email: 'ava.sinclair@gmail.com',
    phone: '+1 (415) 332-9012',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Friend',
    plusOnes: 0,
  },
  {
    id: 'g-24',
    name: 'Liam O’Connor',
    email: 'liam.oconnor@gmail.com',
    phone: '+1 (415) 441-5509',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Childhood Friend',
    plusOnes: 1,
  },
  {
    id: 'g-25',
    name: 'Hannah Brooks',
    email: 'hannah.brooks@gmail.com',
    phone: '+1 (408) 890-4412',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Friend',
    plusOnes: 0,
  },
  {
    id: 'g-26',
    name: 'Samuel Hayes',
    email: 'sam.hayes@gmail.com',
    phone: '+1 (415) 778-9012',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Cousin',
    plusOnes: 1,
  },
  {
    id: 'g-27',
    name: 'Mia Takahashi',
    email: 'mia.takahashi@gmail.com',
    phone: '+1 (510) 991-3321',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Friend',
    plusOnes: 1,
    dietary: 'Dairy-Free',
  },
  {
    id: 'g-28',
    name: 'Oliver King',
    email: 'oliver.king@gmail.com',
    phone: '+1 (415) 678-1123',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Friend',
    plusOnes: 0,
  },
  {
    id: 'g-29',
    name: 'Isabella Rossi',
    email: 'isabella.rossi@gmail.com',
    phone: '+1 (415) 345-6789',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Cousin',
    plusOnes: 1,
  },
  {
    id: 'g-30',
    name: 'Julian Vance Sr.',
    email: 'jvance.sr@gmail.com',
    phone: '+1 (650) 789-0123',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Grandparent',
    plusOnes: 1,
  },
  {
    id: 'g-31',
    name: 'Dorothy Vance',
    email: 'dorothy.vance@gmail.com',
    phone: '+1 (650) 789-0124',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Grandparent',
    plusOnes: 0,
  },
  {
    id: 'g-32',
    name: 'Jack Morrison',
    email: 'jack.morrison@gmail.com',
    phone: '+1 (415) 456-7890',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Mentor',
    plusOnes: 1,
  },
  {
    id: 'g-33',
    name: 'Rachel Sterling',
    email: 'rachel.sterling@gmail.com',
    phone: '+1 (415) 567-8901',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Sister of Groom',
    plusOnes: 1,
  },
  {
    id: 'g-34',
    name: 'Kevin Sterling',
    email: 'kevin.sterling@gmail.com',
    phone: '+1 (415) 678-9012',
    group: 'attending',
    rsvpStatus: 'attending',
    partyTag: 'Brother-in-law',
    plusOnes: 0,
  },

  // Remaining Guests (8 guests = 42 total, currently pending / declined / general invite)
  {
    id: 'g-35',
    name: 'Duhita Biswas',
    email: 'duhitabiswas95156@gmail.com', // User's email from metadata!
    phone: '+1 (415) 555-0199',
    group: 'all',
    rsvpStatus: 'pending',
    partyTag: 'Honored Guest',
    plusOnes: 1,
  },
  {
    id: 'g-36',
    name: 'Natalie Portman-Wood',
    email: 'natalie.wood@gmail.com',
    phone: '+1 (415) 789-3344',
    group: 'all',
    rsvpStatus: 'pending',
    partyTag: 'College Friend',
    plusOnes: 1,
  },
  {
    id: 'g-37',
    name: 'George Washington-Smith',
    email: 'george.smith@gmail.com',
    phone: '+1 (510) 654-3210',
    group: 'all',
    rsvpStatus: 'declined',
    partyTag: 'Family Friend',
    plusOnes: 0,
  },
  {
    id: 'g-38',
    name: 'Victoria Song',
    email: 'victoria.song@gmail.com',
    phone: '+1 (408) 123-4567',
    group: 'all',
    rsvpStatus: 'pending',
    partyTag: 'Coworker',
    plusOnes: 1,
  },
  {
    id: 'g-39',
    name: 'Brandon Hughes',
    email: 'brandon.hughes@gmail.com',
    phone: '+1 (415) 890-1122',
    group: 'all',
    rsvpStatus: 'declined',
    partyTag: 'Friend',
    plusOnes: 0,
  },
  {
    id: 'g-40',
    name: 'Camila Rodriguez',
    email: 'camila.rodriguez@gmail.com',
    phone: '+1 (510) 789-6543',
    group: 'all',
    rsvpStatus: 'pending',
    partyTag: 'Cousin',
    plusOnes: 1,
  },
  {
    id: 'g-41',
    name: 'Timothy Scott',
    email: 'tim.scott@gmail.com',
    phone: '+1 (415) 321-7654',
    group: 'all',
    rsvpStatus: 'pending',
    partyTag: 'Friend',
    plusOnes: 0,
  },
  {
    id: 'g-42',
    name: 'Penelope Cruz-Miller',
    email: 'penelope.cm@gmail.com',
    phone: '+1 (650) 432-1098',
    group: 'all',
    rsvpStatus: 'pending',
    partyTag: 'Friend',
    plusOnes: 1,
  },
];
