import { ScheduleItem } from './types';

export const INITIAL_SCHEDULE_ITEMS: ScheduleItem[] = [
  {
    id: 'event-1',
    name: 'Rehearsal Dinner',
    description: 'Let’s kick off the wedding festivities with some of our favorite dishes at the rehearsal dinner.',
    timingMode: 'start_only',
    date: '2027-09-16',
    formattedDate: 'Thursday, September 16, 2027',
    startTime: '04:00 PM',
    endTime: '08:00 PM',
    timezone: 'GMT+05:30 Kolkata',
    format: 'in_person',
    venue: 'The Waterfront Pavilion, Sunset Bay',
    audience: 'All Guests',
    isDateTBA: false,
    order: 1,
  },
  {
    id: 'event-2',
    name: 'Rehearsal',
    description: 'Walkthrough of ceremony proceedings with the bridal party and immediate family.',
    timingMode: 'tba',
    date: '',
    formattedDate: 'Date To Be Announced',
    startTime: '02:00 PM',
    timezone: 'GMT+05:30 Kolkata',
    format: 'in_person',
    venue: 'Main Sanctuary',
    audience: 'All Guests',
    isDateTBA: true,
    order: 2,
  },
  {
    id: 'event-3',
    name: 'Ceremony and Reception',
    description: 'Our exchange of vows in the garden followed by dinner, dancing, and celebratory toasts into the night.',
    timingMode: 'tba',
    date: '',
    formattedDate: 'Date To Be Announced',
    startTime: '05:00 PM',
    timezone: 'GMT+05:30 Kolkata',
    format: 'in_person',
    venue: 'Grand Botanical Gardens & Ballroom',
    audience: 'All Guests',
    isDateTBA: true,
    order: 3,
  },
  {
    id: 'event-4',
    name: 'Shuttle Bus 🚌',
    description: 'Complimentary shuttle service departing from the partner hotels directly to the event entrance.',
    timingMode: 'tba',
    date: '',
    formattedDate: 'Date To Be Announced',
    startTime: '04:00 PM',
    timezone: 'GMT+05:30 Kolkata',
    format: 'in_person',
    venue: 'Hotel Lobby Pick-up Bay',
    audience: 'All Guests',
    isDateTBA: true,
    order: 4,
  },
];
